apiVersion: apps/v1
kind: Deployment
metadata:
  name: consoleapp-deployment
  labels:
    app: consoleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consoleapp
  template:
    metadata:
      labels:
        app: consoleapp
    spec:
      containers:
      - name: consoleapp
        image: acr1registry.azurecr.io/consoleapp:289 # use your ACR image path
        ports:
        - containerPort: 80
