apiVersion: apps/v1
kind: Deployment
metadata:
  name: consoleapp
  namespace: consoleapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consoleapp
  template:
    metadata:
      labels:
        app: consoleapp
    spec:
      containers:
      - name: consoleapp
        image: acr1registry.azurecr.io/consoleapp:299
        ports:
        - containerPort: 80
