apiVersion: v1
kind: Service
metadata:
  name: consoleapp-service
  namespace: consoleapp-ns
spec:
  selector:
    app: consoleapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
