apiVersion: v1
kind: Service
metadata:
  name: consoleapp-service
  namespace: consoleapp-dev
spec:
  selector:
    app: consoleapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
